name: chat
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.3

dependencies:
  auto_injector: ^2.0.2
  dart_jsonwebtoken: ^2.12.0
  dsql: ^0.0.9+6
  shelf_express:
    path: ../packages/shelf_express

dev_dependencies:
  faker_x: ^0.6.16
  lints: ^2.0.0
  test: ^1.21.0
